name: 'Flutter Android Debug'
on: [push]
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    # Get flutter packages
    - run: cd ANDROID IOS = DART FLUTTER/tp_cc_restful_api && flutter packages pub get
    - run: flutter packages pub get
    # Build :D 
    - run: flutter build apk --debug
