name: 'Flutter Android Debug'
on: push
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: install dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: pub get
        path: "ANDROID IOS = DART FLUTTER/tp_cc_restful_api/" # Line 22
        
    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --debug
        path: "ANDROID IOS = DART FLUTTER/tp_cc_restful_api/" # Line 22
        
