name: 'Flutter Android Debug'
on: push
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hello world
        run: |
          echo "/home/runner/work/TP-CC-MASTER-2-RSID/TP-CC-MASTER-2-RSID/ANDROID IOS = DART FLUTTER/tp_cc_restful_api/build/app/outputs/apk/release/app-release.apk"
          echo GITHUB_WORKSPACE= $GITHUB_WORKSPACE
          echo GITHUB_WORKFLOW= $GITHUB_WORKFLOW
          echo GITHUB_ACTION= $GITHUB_ACTION
          echo GITHUB_ACTOR= $GITHUB_ACTOR
          echo GITHUB_REPOSITORY= $GITHUB_REPOSITORY
          echo PATH_TO_APK= $PATH_TO_APK
        env:
          FLUTTER_DEFAULT_APK_PATH: "/build/app/outputs/apk/release/app-release.apk"
          PATH_TO_FOLDER_SOURCE: "/ANDROID IOS = DART FLUTTER/tp_cc_restful_api"
          PATH_TO_APK: ${{GITHUB_WORKSPACE}} ${{PATH_TO_FOLDER_SOURCE}} ${{FLUTTER_DEFAULT_APK_PATH}}
          
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '12.x'
#       - uses: subosito/flutter-action@v1
#         with:
#           flutter-version: '1.7.8+hotfix.4'
      
#       - name: Install dependencies
#         working-directory: ./ANDROID IOS = DART FLUTTER/tp_cc_restful_api
#         run: flutter pub get
      
#       - name: build apk
#         working-directory: ./ANDROID IOS = DART FLUTTER/tp_cc_restful_api
#         run: flutter build apk
        
#       - name: Upload apk to artifacts
#         uses: actions/upload-artifact@v1
#         with:
#           name: homework
#           path: ./ANDROID IOS = DART FLUTTER/tp_cc_restful_api/build/app/outputs/apk/release/app-release.apk
          
#       - name: Upload to release
#         uses: JasonEtco/upload-to-release@master
#         with:
#           args: "/home/runner/work/TP-CC-MASTER-2-RSID/TP-CC-MASTER-2-RSID/ANDROID IOS = DART FLUTTER/tp_cc_restful_api/build/app/outputs/apk/release/app-release.apk"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#########################################################
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           body: |
#             Changes in this Release
#             - First Change
#             - Second Change
#           draft: false
#           prerelease: false    

 
          
        
