name: build and test app
on: [push]
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: steebchen/flutter@v1.0.0
      with:
        args: cd ANDROID IOS = DART FLUTTER/tp_cc_restful_api && flutter packages pub get

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: cd ANDROID IOS = DART FLUTTER/tp_cc_restful_api && flutter build apk --debug
